#!/bin/bash

# Cleanup script for flglaucomasegfinal repository
# This removes old/conflicting directories before running driver scripts with --skip-training
# 
# Usage: bash cleanup_old_structure.sh [--dry-run]
#   --dry-run: Show what would be removed without actually removing

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

DRY_RUN=0
if [ "$1" = "--dry-run" ]; then
    DRY_RUN=1
    echo "🔍 DRY RUN MODE - No files will be deleted"
    echo ""
fi

# Function to remove directory with confirmation
remove_dir() {
    local dir=$1
    local reason=$2
    
    if [ -d "$dir" ]; then
        local size=$(du -sh "$dir" 2>/dev/null | cut -f1)
        echo "📁 Found: $dir (Size: $size)"
        echo "   Reason: $reason"
        
        if [ $DRY_RUN -eq 1 ]; then
            echo "   [DRY RUN] Would remove this directory"
        else
            echo "   ✅ Removing..."
            rm -rf "$dir"
            echo "   ✓ Removed"
        fi
        echo ""
    else
        echo "⚪ Not found: $dir (already clean)"
        echo ""
    fi
}

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║       Cleanup Script for flglaucomasegfinal Repository        ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Current directory: $SCRIPT_DIR"
echo ""

if [ $DRY_RUN -eq 0 ]; then
    echo "⚠️  WARNING: This will DELETE the following directories:"
    echo "   • metrics/"
    echo "   • inference/"
    echo "   • plot_generation_toolkit/"
    echo "   • outputs/sk_train_mask2former/"
    echo "   • outputs/test_train_fl_global_eval_weighted_batch8/"
    echo ""
    echo "   Optional (will be regenerated):"
    echo "   • outputs/pipeline2/"
    echo "   • outputs/pipeline3/"
    echo "   • outputs/pipeline4/"
    echo ""
    read -p "Continue? (yes/no): " confirm
    
    if [ "$confirm" != "yes" ]; then
        echo "❌ Cleanup cancelled."
        exit 0
    fi
    echo ""
fi

echo "════════════════════════════════════════════════════════════════"
echo "REMOVING OLD/CONFLICTING DIRECTORIES"
echo "════════════════════════════════════════════════════════════════"
echo ""

# Remove old metrics directory (replaced by scores/)
remove_dir "metrics" "Replaced by 'scores/' directory in new structure"

# Remove old inference directory (replaced by outputs/)
remove_dir "inference" "Not in final structure - outputs go to 'outputs/'"

# Remove plot generation toolkit (replaced by root-level plots/)
remove_dir "plot_generation_toolkit" "Replaced by root-level 'plots/' directory"

# Remove old non-standard output directories
remove_dir "outputs/sk_train_mask2former" "Old run with non-standard naming convention"
remove_dir "outputs/test_train_fl_global_eval_weighted_batch8" "Old run with non-standard naming convention"

echo "════════════════════════════════════════════════════════════════"
echo "OPTIONAL: REMOVE EXISTING OUTPUTS (WILL BE REGENERATED)"
echo "════════════════════════════════════════════════════════════════"
echo ""

# Optional: Remove existing pipeline outputs
if [ $DRY_RUN -eq 0 ]; then
    read -p "Remove outputs/pipeline2, pipeline3, pipeline4? (yes/no): " confirm_outputs
    echo ""
    if [ "$confirm_outputs" = "yes" ]; then
        remove_dir "outputs/pipeline2" "Will be regenerated by driver scripts"
        remove_dir "outputs/pipeline3" "Will be regenerated by driver scripts"
        remove_dir "outputs/pipeline4" "Will be regenerated by driver scripts"
    else
        echo "⚪ Keeping existing pipeline outputs (will be overwritten)"
        echo ""
    fi
else
    echo "[DRY RUN] Would ask about removing outputs/pipeline2, pipeline3, pipeline4"
    echo ""
fi

echo "════════════════════════════════════════════════════════════════"
echo "CLEANUP SUMMARY"
echo "════════════════════════════════════════════════════════════════"
echo ""

if [ $DRY_RUN -eq 1 ]; then
    echo "🔍 DRY RUN COMPLETE - No files were deleted"
    echo ""
    echo "To actually perform the cleanup, run:"
    echo "  bash cleanup_old_structure.sh"
    echo ""
else
    echo "✅ Cleanup complete!"
    echo ""
    echo "Current structure:"
    ls -d */ 2>/dev/null | grep -v "^data/\|^metadata/\|^engine/\|^driver/\|^models/\|^outputs/" || echo "  (only core directories remain)"
    echo ""
    echo "You can now run driver scripts with --skip-training:"
    echo ""
    echo "  bash driver/pipeline1.sh --skip-training"
    echo "  bash driver/pipeline2.sh --skip-training"
    echo "  bash driver/pipeline3.sh --skip-training"
    echo "  bash driver/centraltrain.sh --skip-training"
    echo "  bash driver/persite.sh all sequential --skip-training"
    echo "  bash driver/pipeline4.sh all sequential --skip-training"
    echo ""
    echo "This will generate:"
    echo "  ✓ outputs/        - Inference predictions"
    echo "  ✓ scores/         - Evaluation metrics"
    echo "  ✓ Statistics/     - Statistical test results"
    echo "  ✓ plots/          - Publication-ready visualizations"
    echo ""
fi

echo "════════════════════════════════════════════════════════════════"

