python3 train_mask2former.py \
    --train_csv /sddata/data/retina_datasets_preprocessed/federated_learning_public/csvs/combined_train.csv \
    --val_csv /sddata/data/retina_datasets_preprocessed/federated_learning_public/csvs/combined_val.csv \
    --csv_img_path_col image_path \
    --csv_label_path_col label_path \
    --output_directory /home/thakuriu/fl_glaucoma_seg/detection_segmentation_v2/segmentation_train_and_inference/train_outputs \
    --dataset_mean 0.768 0.476 0.289 \
    --dataset_std 0.221 0.198 0.165 \
    --lr 0.00003 \
    --batch_size 8 \
    --jitters 0.2 0.2 0.05 0.05 0.75 \
    --num_epochs 100 \
    --patience 7 \
    --num_val_outputs_to_save 5 \
    --num_workers 16